# runtime: python39

# entrypoint: gunicorn -b :$PORT finalCode:app

# handlers:
# - url: /.*
#   script: auto

# env_variables:
#   FLASK_ENV: development
runtime: python39

entrypoint: gunicorn -b :$PORT finalcode:app

instance_class: F2  # Adjust based on your needs

automatic_scaling:
  min_instances: 1
  max_instances: 10  # Adjust this value as needed


handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

env_variables:
  FLASK_ENV: production  # Set to production for stability
